### ISSUE TITLE
BUG API 接口随意访问，未受保护

### ISSUE THREAD

**Issue by benzBrake** [idealclover/AISummary-Typecho#4]
看了一下源码，接口可以直接访问
https://github.com/idealclover/AISummary-Typecho/blob/f352585d94f9c89abceb6af8f586dc452650e409/Action.php#L48-L60

我的一般做法是增加一个选项，启用插件的时候随机生成请求令牌
```
$token = new Typecho_Widget_Helper_Form_Element_Text('token', NULL, self::create_uuid(), _t('请求令牌'), _t('用于验证请求合法性'));
$form->addInput($token);
```

**Comment by OP404OP** [comment]
你好这个随机请求令牌代码加在哪里呢

**Comment by idealclover** [comment]
#5 @benzBrake 感谢指正！出了一般fix 哥们有空可以帮review下~

**Comment by OP404OP** [comment]
我是整不明白，找GPT一顿反复询问，加了几行代码，不知道对不对，我看反正能正常使用。

Plugin.php

`  	public static function create_uuid()
    {
      // 生成一个简化的 UUID
      return sprintf(
        '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        mt_rand(0, 0xffff), mt_rand(0, 0xffff),
        mt_rand(0, 0xffff),
        mt_rand(0, 0x0fff) | 0x4000,
        mt_rand(0, 0x3fff) | 0x8000,
        mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
        );
    
    }`
        // 添加输入框：key值
        $keyValue = new Typecho_Widget_Helper_Form_Element_Text(
            'keyValue',
            NULL,
            NULL,
            _t('API KEY'),
            _t('请输入调用 API 的 key')
        );

**Comment by idealclover** [comment]
@OP404OP  #5 dev分支中已经给了一版解决方案 你可以直接用那个分支的代码 只是我还没合master



> 我是整不明白，找GPT一顿反复询问，加了几行代码，不知道对不对，我看反正能正常使用。
> 
> Plugin.php
> ``public static function create_uuid()
>     {
>       // 生成一个简化的 UUID
>       return sprintf(
>         '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
>         mt_rand(0, 0xffff), mt_rand(0, 0xffff),
>         mt_rand(0, 0xffff),
>         mt_rand(0, 0x0fff) | 0x4000,
>         mt_rand(0, 0x3fff) | 0x8000,
>         mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
>         );
>     
>     }
>         // 添加输入框：key值
>         $keyValue = new Typecho_Widget_Helper_Form_Element_Text(
>             'keyValue',
>             NULL,
>             NULL,
>             _t('API KEY'),
>             _t('请输入调用 API 的 key')
>         );``

**Comment by OP404OP** [comment]
欧克

**Comment by OP404OP** [comment]
> @OP404OP #5 dev分支中已经给了一版解决方案 你可以直接用那个分支的代码 只是我还没合master
> 
> > 我是整不明白，找GPT一顿反复询问，加了几行代码，不知道对不对，我看反正能正常使用。
> > Plugin.php
> > ``public static function create_uuid()
> > {
> > // 生成一个简化的 UUID
> > return sprintf(
> > '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
> > mt_rand(0, 0xffff), mt_rand(0, 0xffff),
> > mt_rand(0, 0xffff),
> > mt_rand(0, 0x0fff) | 0x4000,
> > mt_rand(0, 0x3fff) | 0x8000,
> > mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
> > );
> > ```
> > }
> >     // 添加输入框：key值
> >     $keyValue = new Typecho_Widget_Helper_Form_Element_Text(
> >         'keyValue',
> >         NULL,
> >         NULL,
> >         _t('API KEY'),
> >         _t('请输入调用 API 的 key')
> >     );``
> > ```

OK。
